version: '3.8'

services:

  web:
    image: mjhea0/flask-docker-swarm_web:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    expose:
      - 5000
    environment:
      - FLASK_ENV=development
      - DB_USER=postgres
      - DB_PASSWORD=gr0upseven
      - SECRET_CODE=password
    depends_on:
      - db
    networks:
      - app

  db:
    image: postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - data-volume:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=gr0upseven
    networks:
      - app

networks:
  app:
    driver: overlay

volumes:
  data-volume:
    driver: local
